name = "budget_fe"
target = "javascript"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

gleam = ">= 1.9.0"

[dependencies]
gleam_stdlib = "~> 0.58.0"
lustre = "~> 4.6.4"
lustre_http = "~> 0.7.0"
modem = "~> 2.0.1"
gluid = ">= 1.1.0 and < 2.0.0"
rada = ">= 0.5.0 and < 1.0.0"
gleam_json = "~> 2.3.0"
budget_shared = { path = "../budget_shared" }
decode = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
