name = "budget_fe"
target = "javascript"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

gleam = ">= 1.10.0"

[dependencies]
gleam_stdlib = "~> 0.58.0"
lustre = "~> 4.6.4"
lustre_http = "~> 0.7.0"
modem = "~> 2.0.1"
rada = ">= 0.5.0 and < 1.0.0"
gleam_json = "~> 2.3.0"
budget_shared = { git = "https://github.com/sgrekov/BudgetDomain.git", ref = "6c10e976b87857ddd9f79c169a933de25d47e1cd" }
# budget_shared = { path = "../budget_shared" }
decode = ">= 1.1.0 and < 2.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gwt = ">= 2.0.0 and < 3.0.0"
# youid = { git = "https://github.com/sgrekov/youid", ref = "dd17cbab9e8de6c6366bcfedc4ff1255ec13aec8" }
# youid = ">= 1.4.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
lustre_dev_tools = ">= 1.6.5 and < 2.0.0"
